Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.9"

  config.vm.define "oc" do |oc|
    oc.vm.network "private_network", ip: "192.168.32.11"
    oc.vm.hostname = "oc"
    oc.vm.provider "oc" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
  end

  config.vm.define "cc1" do |cc1|
    cc1.vm.network "private_network", ip: "192.168.32.13"
    cc1.vm.hostname = "cc1"
    cc1.vm.provider "cc1" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
  end

  config.vm.define "cc2" do |cc2|
    cc2.vm.network "private_network", ip: "192.168.32.15"
    cc2.vm.hostname = "cc2"
    cc2.vm.provider "cc2" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
  end
end
